<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Vendas_itens extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Vendas_itens_model');
        $this->load->library('form_validation');
        $this->load->helper("moeda");

    }

    public function index()
    {

    }

    public function read($id) 
    {
        $row = $this->Vendas_model->get_by_id($id);
        if ($row) {
            $data = array(
              'id_vendas' => $row->id_vendas,
              'lk_id_servico' => $row->lk_id_servico,
              'valor' => $row->valor,
              );
            $this->load->view('vendas/VENDAS_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect('vendas');
        }
    }


    
    public function add_venda_item() 
    {
     $valor = str_replace('.','',$this->input->post('valor'));
     $valor = strtr($valor, ',', '.');

     $data = array(
      'lk_id_servico' => 1,//$this->input->post('id_requisicao',TRUE),
      'lk_id_fluxo' => 1,//$this->input->post('descricao',TRUE),
      'valor' =>  $valor,
      'qtd' => $this->input->post('qtd',TRUE)
      );
     if(validar($this->input->post('valor'))){
       $this->Vendas_itens_model->insert($data);
       echo json_encode(array('result'=> true));
   }else{
    echo json_encode(array('result'=> FALSE, 'msg' => 'Valor não está no formado Brasleiro'));

}  
}


public function delete() 
    {
       $id =  $this->input->post('iditem',TRUE);

        $row = $this->Vendas_itens_model->get_by_id($id);

        if ($row) {
            $this->Vendas_itens_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
             echo json_encode(array('result'=> true));

        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            echo json_encode(array('result'=> false));
        }

    }

public function update($id) 
{
    $row = $this->Vendas_model->get_by_id($id);

    if ($row) {
        $data = array(
            'button' => 'Update',
            'action' => site_url('vendas/update_action'),
            'id_vendas' => set_value('id_vendas', $row->id_vendas),
            'lk_id_servico' => set_value('lk_id_servico', $row->lk_id_servico),
            'valor' => set_value('valor', $row->valor),
            );
        $this->load->view('vendas/VENDAS_form', $data);
    } else {
        $this->session->set_flashdata('message', 'Record Not Found');
        redirect('vendas');
    }
}

public function update_action() 
{
    $this->_rules();

    if ($this->form_validation->run() == FALSE) {
        $this->update($this->input->post('id_vendas', TRUE));
    } else {
        $data = array(
          'lk_id_servico' => $this->input->post('lk_id_servico',TRUE),
          'valor' => $this->input->post('valor',TRUE),
          );

        $this->Vendas_model->update($this->input->post('id_vendas', TRUE), $data);
        $this->session->set_flashdata('message', 'Update Record Success');
        redirect('vendas');
    }
}



public function _rules() 
{
	$this->form_validation->set_rules('lk_id_servico', 'lk id servico', 'trim|required');
	$this->form_validation->set_rules('valor', 'valor', 'trim|required|numeric');

	$this->form_validation->set_rules('id_vendas', 'id_vendas', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
}

}

/* End of file Vendas.php */
/* Location: ./application/controllers/Vendas.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-02 14:59:18 */
/* http://harviacode.com */