<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Caixa_model extends CI_Model
{

    public $table = 'CAIXA';
    public $id = 'id_caixa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_caixa_aberto($id_login)
    {
        $this->db->where('id_login_abertura', $id_login);
        $this->db->where('id_login_fechamento', 0);
        return $this->db->get($this->table)->row();
    }
    
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_caixa', $q);
	$this->db->or_like('caixa_saldo', $q);
	$this->db->or_like('data_abertura', $q);
	$this->db->or_like('data_fechamento', $q);
	$this->db->or_like('id_login_abertura', $q);
	$this->db->or_like('id_login_fechamento', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_caixa', $q);
	$this->db->or_like('caixa_saldo', $q);
	$this->db->or_like('data_abertura', $q);
	$this->db->or_like('data_fechamento', $q);
	$this->db->or_like('id_login_abertura', $q);
	$this->db->or_like('id_login_fechamento', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Caixa_model.php */
/* Location: ./application/models/Caixa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-29 13:25:55 */
/* http://harviacode.com */