<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Servico_model extends CI_Model
{

    public $table = 'SERVICO';
    public $id = 'id_servico';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->load->helper("moeda");

    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_servico', $q);
        $this->db->or_like('nome', $q);
        $this->db->or_like('valor_base', $q);
        $this->db->or_like('st_servico', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_servico', $q);
        $this->db->or_like('nome', $q);
        $this->db->or_like('valor_base', $q);
        $this->db->or_like('st_servico', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function autoCompleteServico($q){

        $this->db->select('*');
        $this->db->limit(5);
        $this->db->like('nome', $q);
        $query = $this->db->get($this->table);
        if($query->num_rows() > 0){
            foreach ($query->result_array() as $row){
                $row_set[] = array('label'=>$row['nome'].' | Valor Base: '.rs($row['valor_base']),'valor_base'=>rs($row['valor_base']));
            }
            echo json_encode($row_set);
        }
    }

}

/* End of file Servico_model.php */
/* Location: ./application/models/Servico_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-02 14:32:07 */
/* http://harviacode.com */